---
- name: Install Composer
  hosts: "{{ host }}"
  remote_user: "{{user}}"
  become: yes
  gather_facts: no
  tasks:
    - name: Install dependencies
      apt:
        name: ['curl', 'php-cli', 'php-mbstring', 'git']
        state: present

    - name: Download Composer installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/installer

    - name: Run Composer installer
      command: php /tmp/installer --install-dir=/usr/local/bin --filename=composer

    - name: Set Composer permissions
      command: chmod +x /usr/local/bin/composer
