---
- name: Install requirements
  hosts: "{{ host }}"
  remote_user: "{{user}}"
  become: yes
  gather_facts: no
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: yes
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      ansible.builtin.apt:
        update_cache: yes
      